#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
export EDITOR="$HOME/.local/bin/nvim"
export DEFAULT_USER=$USER
export KEYTIMEOUT=1
alias vim="$HOME/.local/bin/nvim"

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

source  /etc/bash_completion.d/g4d
source  /etc/bash_completion.d/hgd

# Source the common XManager bashrc, only adds convenience functions for
# XManager.
if [ -r /google/data/ro/teams/dmgi/configs/google_xm_bashrc ] ; then
  source /google/data/ro/teams/dmgi/configs/google_xm_bashrc
fi

export XM_DEFAULT_POOL="x"
export XM_DEFAULT_RESOURCE_ALLOC="group:x/early-pipeline-alloc"
export FZF_DEFAULT_COMMAND='fdfind'
